### ISSUE TITLE
Метрополитен-1

### ISSUE THREAD

**Issue by Levmas25** [Levmas25/BIBA#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- А куда в классе Station убежал параметр transfers из конструктора? Нужно вернуть.
- Файлы .cs следует называть так же, как и имена классов. Переименуй их.
- Ты удалил класс Program. При компиляции вижка будет грустить, так как не найдет метод main() 🥺 нужно вернуть обратно.

**Comment by vdetstvepil** [comment]
Поправишь косяки и тогда зачту.

**Comment by Levmas25** [comment]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Параметр transfers ты вернул, только ты в конструкторе присваиваешь ссылку на список, а не копируешь элементы из одного списка в другой. Воспользуйся функцией AddRange или через цикл foreach скопируй элементы. Поправишь этот момент и приму.

**Comment by Levmas25** [comment]
@vdetstvepil подправил

**Comment by vdetstvepil** [comment]
Принято.

**Comment by vdetstvepil** [comment]
Закрой самостоятельно свой issue и добавь, пожалуйста, преподавателей в свой репозиторий, а то мы закрывать issue сами не можем.
