### ISSUE TITLE
WPF

### ISSUE THREAD

**Issue by Levmas25** [Levmas25/BIBA#4]
@GalteXx

**Comment by GalteXx** [comment]
Ты код не приложил.
A sln это файл решения VS. Он при проверке не имеет значения. Если не хочешь кидать лишних файлов, то нужно прикладывать MainWindow.xaml и MainWindow.xaml.cs

**Comment by Levmas25** [comment]
@GalteXx

**Comment by GalteXx** [comment]
По 10 стингеров будет сниматься при дальнейшем списывании...
Советую переделать ДЗ легитимно.
